package service

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"
)

// SkeletonTask is the minimal task info needed for a skeleton dev plan.
type SkeletonTask struct {
	ID      string
	Summary string
}

// WriteSkeletonDevPlanResult is the result of WriteSkeletonDevPlan.
type WriteSkeletonDevPlanResult struct {
	DocID    string // document record ID
	FilePath string // relative path from repo root
	Action   string // "created", "updated", or "skipped"
}

// buildSkeletonDevPlan produces a skeleton dev-plan Markdown document from
// feature metadata and a list of tasks. The output is valid UTF-8 Markdown
// that conforms to the REQ-002 structure.
func buildSkeletonDevPlan(featureName, featureID string, applyDate time.Time, tasks []SkeletonTask) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Dev Plan: %s (Decomposed)\n\n", featureName)

	fmt.Fprintf(&b, "| Field   | Value |\n")
	fmt.Fprintf(&b, "|---------|-------|\n")
	fmt.Fprintf(&b, "| Feature | %s |\n", featureID)
	fmt.Fprintf(&b, "| Created | %s |\n", applyDate.Format("2006-01-02"))
	fmt.Fprintf(&b, "| Method  | decompose apply (auto-generated) |\n")
	fmt.Fprintf(&b, "| Status  | Draft |\n\n")

	fmt.Fprintf(&b, "## Overview\n\n")
	fmt.Fprintf(&b, "This dev plan was automatically generated by `decompose(action: \"apply\")`.\n")
	fmt.Fprintf(&b, "It represents the task breakdown produced by the decompose workflow.\n\n")

	fmt.Fprintf(&b, "## Tasks\n\n")
	fmt.Fprintf(&b, "| Task ID | Summary |\n")
	fmt.Fprintf(&b, "|---------|----------|\n")
	for _, t := range tasks {
		fmt.Fprintf(&b, "| %s | %s |\n", t.ID, t.Summary)
	}
	fmt.Fprintf(&b, "\n")

	result := b.String()
	// Guard: ensure the output is valid UTF-8. Pure string operations should
	// always produce valid UTF-8, but this makes the guarantee explicit.
	if !utf8.ValidString(result) {
		result = strings.ToValidUTF8(result, "\uFFFD")
	}
	return result
}

// WriteSkeletonDevPlan creates or updates the auto-generated skeleton dev-plan
// for a feature after decompose apply. It handles three cases:
//
//   - No dev-plan exists → write file, register + auto-approve (REQ-001)
//   - Non-skeleton dev-plan exists (path differs from convention) → skip (REQ-003)
//   - Skeleton already exists → overwrite file, refresh + re-approve (REQ-004)
//
// Returns "skipped" (no error) when tasks is empty (REQ-006).
func (s *DecomposeService) WriteSkeletonDevPlan(featureID string, tasks []SkeletonTask) (WriteSkeletonDevPlanResult, error) {
	// REQ-006: only write a skeleton when at least one task was created.
	if len(tasks) == 0 {
		return WriteSkeletonDevPlanResult{Action: "skipped"}, nil
	}

	// Load the feature to get slug and name.
	feat, err := s.entitySvc.Get("feature", featureID, "")
	if err != nil {
		return WriteSkeletonDevPlanResult{}, fmt.Errorf("load feature %s: %w", featureID, err)
	}
	featureSlug, _ := feat.State["slug"].(string)
	featureName, _ := feat.State["name"].(string)
	if featureName == "" {
		featureName = featureSlug
	}

	// Canonical skeleton path for this feature.
	skeletonPath := "work/dev-plan/" + featureSlug + "-decomposed.md"

	// List all dev-plan docs owned by this feature (any status).
	docs, err := s.docSvc.ListDocuments(DocumentFilters{Owner: featureID, Type: "dev-plan"})
	if err != nil {
		return WriteSkeletonDevPlanResult{}, fmt.Errorf("list dev-plan docs for %s: %w", featureID, err)
	}

	// Check whether any non-skeleton dev-plan exists. If so, skip silently.
	for _, d := range docs {
		if d.Path != skeletonPath {
			return WriteSkeletonDevPlanResult{Action: "skipped"}, nil
		}
	}

	// Find the existing skeleton record, if any.
	var existingDocID string
	for _, d := range docs {
		if d.Path == skeletonPath {
			existingDocID = d.ID
			break
		}
	}

	// Build skeleton content.
	content := buildSkeletonDevPlan(featureName, featureID, time.Now(), tasks)

	// Write (or overwrite) the file on disk.
	repoRoot := s.docSvc.RepoRoot()
	fullPath := filepath.Join(repoRoot, skeletonPath)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return WriteSkeletonDevPlanResult{}, fmt.Errorf("mkdir for skeleton dev plan: %w", err)
	}
	if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
		return WriteSkeletonDevPlanResult{}, fmt.Errorf("write skeleton dev plan: %w", err)
	}

	if existingDocID == "" {
		// New skeleton: register with auto-approve.
		result, err := s.docSvc.SubmitDocument(SubmitDocumentInput{
			Path:        skeletonPath,
			Type:        "dev-plan",
			Title:       "Dev Plan: " + featureName + " (Decomposed)",
			Owner:       featureID,
			CreatedBy:   "decompose apply",
			AutoApprove: true,
		})
		if err != nil {
			return WriteSkeletonDevPlanResult{}, fmt.Errorf("register skeleton dev plan: %w", err)
		}
		return WriteSkeletonDevPlanResult{
			DocID:    result.ID,
			FilePath: skeletonPath,
			Action:   "created",
		}, nil
	}

	// Existing skeleton: refresh the content hash (resets approved→draft if content changed),
	// then re-approve if the document is now in draft status.
	refreshResult, err := s.docSvc.RefreshDocument(RefreshDocumentInput{ID: existingDocID})
	if err != nil {
		return WriteSkeletonDevPlanResult{}, fmt.Errorf("refresh skeleton dev plan %s: %w", existingDocID, err)
	}

	if refreshResult.Status == "draft" {
		if _, err := s.docSvc.ApproveDocument(ApproveDocumentInput{
			ID:         existingDocID,
			ApprovedBy: "decompose apply",
		}); err != nil {
			return WriteSkeletonDevPlanResult{}, fmt.Errorf("re-approve skeleton dev plan %s: %w", existingDocID, err)
		}
	}

	return WriteSkeletonDevPlanResult{
		DocID:    existingDocID,
		FilePath: skeletonPath,
		Action:   "updated",
	}, nil
}
