// Code generated by internal/binding/gen from routing.yaml; DO NOT EDIT.

package binding

import "fmt"

// ─── Generated routing constructs ───────────────────────────────────────────

// validStages is the set of all valid stage binding keys.
// It includes all destination keys from the routing table.
var validStages = map[string]bool{
	"batch-reviewing": true,
	"bug-developing": true,
	"bug-reviewing": true,
	"designing": true,
	"dev-planning": true,
	"developing": true,
	"doc-publishing": true,
	"documenting": true,
	"merging": true,
	"researching": true,
	"retro-fixing": true,
	"reviewing": true,
	"specifying": true,
	"verifying": true,
}

// WorkableStatuses lists all lifecycle statuses that are valid pipeline inputs.
// It includes both feature and bug statuses.
var WorkableStatuses = []string{
	"batch-reviewing",
	"designing",
	"dev-planning",
	"developing",
	"doc-publishing",
	"documenting",
	"in-progress",
	"merging",
	"needs-review",
	"researching",
	"retro-fixing",
	"reviewing",
	"specifying",
	"verifying",
}

// routingTable maps lifecycle statuses to their binding keys.
var routingTable = RoutingTable{
	"batch-reviewing": "batch-reviewing",
	"designing": "designing",
	"dev-planning": "dev-planning",
	"developing": "developing",
	"doc-publishing": "doc-publishing",
	"documenting": "documenting",
	"in-progress": "bug-developing",
	"merging": "merging",
	"needs-review": "bug-reviewing",
	"researching": "researching",
	"retro-fixing": "retro-fixing",
	"reviewing": "reviewing",
	"specifying": "specifying",
	"verifying": "verifying",
}

// BugStatusToBindingKey maps a bug lifecycle status to its corresponding
// stage binding key. Only workable bug statuses (in-progress, needs-review)
// return a binding key; all other bug statuses return an error.
func BugStatusToBindingKey(status string) (string, error) {
	switch status {
	case "in-progress":
		return "bug-developing", nil
	case "needs-review":
		return "bug-reviewing", nil
	default:
		return "", fmt.Errorf("bug status %q is out-of-pipeline", status)
	}
}

// BugStatuses lists all known bug lifecycle statuses (both workable and non-workable).
var BugStatuses = []string{
	"cannot-reproduce",
	"closed",
	"duplicate",
	"in-progress",
	"needs-review",
	"needs-rework",
	"not-planned",
	"planned",
	"reported",
	"reproduced",
	"triaged",
	"verifying",
}

// ValidTiers maps valid tier names.
var ValidTiers = map[string]bool{
	"bug_fix": true,
	"critical": true,
	"feature": true,
	"retro_fix": true,
}

// IsValidTier checks if a tier name is valid.
func IsValidTier(tier string) bool {
	return ValidTiers[tier]
}

// bugStatusToBindingKey wraps BugStatusToBindingKey for internal use.
func bugStatusToBindingKey(status string) (string, error) {
	return BugStatusToBindingKey(status)
}
