package binding

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSyncSurface_CountIsFour verifies that the post-Phase-3 sync surface count
// is 4, down from the pre-Phase-3 count of 7. The surfaces are:
//
//  1. .kbz/stage-bindings.yaml — canonical stage descriptions
//  2. internal/binding/routing.yaml — routing companion (code-owned)
//  3. .kbz/roles/ — role definition files
//  4. .kbz/skills/ — skill definition files
//
// Pre-Phase-3, there were 3 additional hand-edited code surfaces:
//   - validStages (hand-edited in model.go)
//   - workableStatuses (hand-edited in pipeline.go)
//   - FeatureStatus* and BugStatus* constants (hand-edited in entities.go)
//
// These 3 are now generated from routing.yaml via go generate, so they are
// no longer independent sync surfaces.
func TestSyncSurface_CountIsFour(t *testing.T) {
	t.Parallel()

	surfaces := syncSurfaces(t)
	if len(surfaces) != 4 {
		t.Errorf("sync surface count = %d, want 4. Surfaces: %v", len(surfaces), surfaces)
	}
}

// TestSyncSurface_RoutingYamlLocation verifies AC-011: routing.yaml lives in
// internal/binding/, not in .kbz/.
func TestSyncSurface_RoutingYamlLocation(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)

	correctPath := filepath.Join(repoRoot, "internal", "binding", "routing.yaml")
	if _, err := os.Stat(correctPath); os.IsNotExist(err) {
		t.Errorf("routing.yaml not found at expected path: %s", correctPath)
	}

	wrongPath := filepath.Join(repoRoot, ".kbz", "routing.yaml")
	if _, err := os.Stat(wrongPath); err == nil {
		t.Errorf("routing.yaml should NOT exist at %s (consumers do not edit it)", wrongPath)
	}
}

// TestSyncSurface_StageBindingsHeaderComment verifies AC-009: the canonical
// stage-bindings.yaml includes a header comment naming the routing ownership
// boundary within its first 20 lines.
func TestSyncSurface_StageBindingsHeaderComment(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)
	path := filepath.Join(repoRoot, ".kbz", "stage-bindings.yaml")

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read stage-bindings.yaml: %v", err)
	}

	content := string(data)
	lines := strings.Split(content, "\n")

	// Check within first 20 lines.
	end := min(20, len(lines))
	snippet := strings.Join(lines[:end], "\n")

	if !strings.Contains(snippet, "internal/binding/router.go") {
		t.Error("stage-bindings.yaml header must name internal/binding/router.go as routing owner")
	}
	if !strings.Contains(snippet, "routing") {
		t.Error("stage-bindings.yaml header must describe routing ownership boundary")
	}
}

// TestSyncSurface_NoHandEditedRoutingTables verifies that the pre-Phase-3
// hand-edited routing constructs (validStages, workableStatuses) no longer
// exist as hand-edited tables. After Phase 3, these are generated by
// router_gen.go from routing.yaml.
func TestSyncSurface_NoHandEditedRoutingTables(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)

	// Check model.go: validStages must not be declared (it's generated).
	modelPath := filepath.Join(repoRoot, "internal", "binding", "model.go")
	modelContent := readFileOrEmpty(t, modelPath)
	if strings.Contains(modelContent, "var validStages = map[string]bool{") {
		t.Error("hand-edited validStages found in model.go — should be generated from routing.yaml via router_gen.go")
	}

	// Check pipeline.go: workableStatuses must not be declared (it's generated).
	pipelinePath := filepath.Join(repoRoot, "internal", "context", "pipeline.go")
	pipelineContent := readFileOrEmpty(t, pipelinePath)
	if strings.Contains(pipelineContent, "var workableStatuses = []string{") {
		t.Error("hand-edited workableStatuses found in pipeline.go — should be generated from routing.yaml via router_gen.go")
	}
}

// TestSyncSurface_GenerateIsIntegratedIntoBuild verifies that the go generate
// directive and Makefile target exist so router_gen.go stays in sync.
func TestSyncSurface_GenerateIsIntegratedIntoBuild(t *testing.T) {
	t.Parallel()

	repoRoot := findRepoRoot(t)

	// Check that router.go has the go:generate directive.
	routerPath := filepath.Join(repoRoot, "internal", "binding", "router.go")
	routerContent := readFileOrEmpty(t, routerPath)
	if !strings.Contains(routerContent, "go:generate") {
		t.Error("router.go must contain a go:generate directive for router_gen.go")
	}

	// Check that the Makefile has a generate target that invokes go generate.
	makefilePath := filepath.Join(repoRoot, "Makefile")
	makefileContent := readFileOrEmpty(t, makefilePath)
	if !strings.Contains(makefileContent, "generate:") {
		t.Error("Makefile must have a generate target")
	}
	if !strings.Contains(makefileContent, "go generate ./internal/binding") {
		t.Error("Makefile generate target must run go generate ./internal/binding/")
	}

	// Check that the generator exists.
	genPath := filepath.Join(repoRoot, "internal", "binding", "gen", "main.go")
	if _, err := os.Stat(genPath); os.IsNotExist(err) {
		t.Errorf("code generator not found at %s", genPath)
	}
}

// TestSyncSurface_GenerateProducesConsistentOutput verifies that running
// go generate produces router_gen.go and that the output compiles. This
// test is skipped if the generator is not runnable in the test environment.
func TestSyncSurface_GenerateProducesConsistentOutput(t *testing.T) {
	// This is an integration test — it verifies the generation pipeline works.
	// Skip in short mode since it invokes go generate.
	if testing.Short() {
		t.Skip("skipping generation integration test in short mode")
	}

	repoRoot := findRepoRoot(t)

	// Verify router_gen.go exists and is not empty.
	genPath := filepath.Join(repoRoot, "internal", "binding", "router_gen.go")
	info, err := os.Stat(genPath)
	if os.IsNotExist(err) {
		t.Fatalf("router_gen.go does not exist — run 'make generate'")
	}
	if err != nil {
		t.Fatalf("cannot stat router_gen.go: %v", err)
	}
	if info.Size() == 0 {
		t.Error("router_gen.go is empty — generation may have failed")
	}

	// Verify router_gen.go contains the expected generated constructs.
	content := readFileOrEmpty(t, genPath)
	required := []string{
		"var validStages",
		"WorkableStatuses",
		"func bugStatusToBindingKey",
		"var routingTable",
		"Code generated",
	}
	for _, r := range required {
		if !strings.Contains(content, r) {
			t.Errorf("router_gen.go must contain %q", r)
		}
	}
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// syncSurfaces returns the list of sync surfaces that exist in the repo.
// These are the canonical sources of truth for routing decisions.
func syncSurfaces(t *testing.T) []string {
	t.Helper()

	repoRoot := findRepoRoot(t)
	var surfaces []string

	// Surface 1: Stage bindings YAML.
	if pathExists(t, filepath.Join(repoRoot, ".kbz", "stage-bindings.yaml")) {
		surfaces = append(surfaces, ".kbz/stage-bindings.yaml")
	}

	// Surface 2: Routing companion YAML.
	if pathExists(t, filepath.Join(repoRoot, "internal", "binding", "routing.yaml")) {
		surfaces = append(surfaces, "internal/binding/routing.yaml")
	}

	// Surface 3: Role files.
	rolesDir := filepath.Join(repoRoot, ".kbz", "roles")
	if entries, err := os.ReadDir(rolesDir); err == nil {
		hasRoles := false
		for _, e := range entries {
			if !e.IsDir() && strings.HasSuffix(e.Name(), ".yaml") {
				hasRoles = true
				break
			}
		}
		if hasRoles {
			surfaces = append(surfaces, ".kbz/roles/")
		}
	}

	// Surface 4: Skill files.
	skillsDir := filepath.Join(repoRoot, ".kbz", "skills")
	if entries, err := os.ReadDir(skillsDir); err == nil {
		hasSkills := false
		for _, e := range entries {
			if e.IsDir() {
				// Check for SKILL.md in each skill directory.
				skillFile := filepath.Join(skillsDir, e.Name(), "SKILL.md")
				if _, err := os.Stat(skillFile); err == nil {
					hasSkills = true
					break
				}
			}
		}
		if hasSkills {
			surfaces = append(surfaces, ".kbz/skills/")
		}
	}

	return surfaces
}


func pathExists(t *testing.T, path string) bool {
	t.Helper()
	_, err := os.Stat(path)
	return err == nil
}

func readFileOrEmpty(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return string(data)
}
